/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteEbg;
import bean.VendaEbg;
import bean.VendaprodutoEbg;
import bean.VendedorEbg;
import dao.Cliente_DAO;
import dao.Venda_DAO;
import dao.Vendaproduto_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util_ebg;

/**
 *
 * @author user
 */
public class JDlgVenda_ebg extends javax.swing.JDialog {
    MaskFormatter mascaraData;
    private boolean incluindo;
    
    VendaEbg vendaEbg;
    Venda_DAO venda_DAO;
    VendaController_ebg vendaController_ebg;
    VendaprodutoEbg vendaprodutoEbg;
    Vendaproduto_DAO vendaproduto_DAO;
    VendaprodutoController_ebg vendaprodutoController_ebg;
    ClienteEbg ClienteEbg;
    JDlgVendaPesquisar_ebg jDlgVendaPesquisa;
    JDlgVendaproduto_ebg JDlgVendaProduto_ebg;
    /**
     * Creates new form JDlgVendas
     */
    
    public JDlgVenda_ebg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas");
        setLocationRelativeTo(null);
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.habilitar(false, jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg, jBtnIncluirProd_ebg, jBtnAlterarProd_ebg, jBtnExcluirProd_ebg, jBtnAlterar_ebg, jBtnCancelar_ebg, jBtnExcluir_ebg, jBtnConfirmar_ebg);
        Util_ebg.limparCampos(jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        venda_DAO = new Venda_DAO();
        
        Cliente_DAO cliente_DAO = new Cliente_DAO();
        List listaCli = cliente_DAO.listAll();
        for (int i = 0; i < listaCli.size(); i++) {
        jCboCliente_ebg.addItem((ClienteEbg) listaCli.get(i));
        
    }
        vendaprodutoController_ebg = new VendaprodutoController_ebg();
        List lista = new ArrayList();
        vendaprodutoController_ebg.setList(lista);
        jTable1.setModel(vendaprodutoController_ebg);
   
    try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgVenda_ebg.class.getName()).log(Level.SEVERE, null, ex);
        }
         jFmtData_ebg.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }

    public VendaEbg viewBean() {
        VendaEbg vendaEbg = new VendaEbg();
        
        vendaEbg.setIdvendaEbg(Util_ebg.strInt(jTxtVenda_ebg.getText()));
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            vendaEbg.setDataEbg(formato.parse(jFmtData_ebg.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        vendaEbg.setVendedorEbg((VendedorEbg)jCboVendedor_ebg.getSelectedItem());
        vendaEbg.setClienteEbg((ClienteEbg)jCboCliente_ebg.getSelectedItem());
        vendaEbg.setTotalvendaEbg(Util_ebg.strDouble(jTxtTotal_ebg.getText()));
        
        return vendaEbg;
    }
    
    public void beanView(VendaEbg vendaEbg){
        String id = String.valueOf(vendaEbg.getIdvendaEbg());
        
        jTxtVenda_ebg.setText(id);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtData_ebg.setText(formato.format (vendaEbg.getDataEbg()));
        jCboCliente_ebg.setSelectedItem(vendaEbg.getClienteEbg());
        jCboVendedor_ebg.setSelectedItem(vendaEbg.getVendedorEbg());
        jTxtTotal_ebg.setText(Util_ebg.doubleStr(vendaEbg.getTotalvendaEbg()));
    }
    
    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFmtData_ebg = new javax.swing.JFormattedTextField();
        jBtnAlterarProd_ebg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtTotal_ebg = new javax.swing.JTextField();
        jCboVendedor_ebg = new javax.swing.JComboBox<VendedorEbg>();
        jBtnExcluirProd_ebg = new javax.swing.JButton();
        jBtnAlterar_ebg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnExcluir_ebg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnConfirmar_ebg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtVenda_ebg = new javax.swing.JTextField();
        jBtnCancelar_ebg = new javax.swing.JButton();
        jBtnPesquisar_ebg = new javax.swing.JButton();
        jCboCliente_ebg = new javax.swing.JComboBox<ClienteEbg>();
        jLabel2 = new javax.swing.JLabel();
        jBtnIncluirProd_ebg = new javax.swing.JButton();
        jBtnIncluir_ebg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFmtData_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtData_ebgActionPerformed(evt);
            }
        });

        jBtnAlterarProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterarProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProd_ebgActionPerformed(evt);
            }
        });

        jLabel3.setText("Vendedor");

        jCboVendedor_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedor_ebgActionPerformed(evt);
            }
        });

        jBtnExcluirProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluirProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProd_ebgActionPerformed(evt);
            }
        });

        jBtnAlterar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_ebg.setText("Alerar");
        jBtnAlterar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ebgActionPerformed(evt);
            }
        });

        jLabel1.setText("Num venda");

        jBtnExcluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_ebg.setText("Excluir");
        jBtnExcluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ebgActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "produto", "quantidade", "valor unitario", "total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnConfirmar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/05 - ok.png"))); // NOI18N
        jBtnConfirmar_ebg.setText("Confirmar");
        jBtnConfirmar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ebgActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        jTxtVenda_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVenda_ebgActionPerformed(evt);
            }
        });

        jBtnCancelar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_ebg.setText("Cancelar");
        jBtnCancelar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ebgActionPerformed(evt);
            }
        });

        jBtnPesquisar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_ebg.setText("Pesquisar");
        jBtnPesquisar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ebgActionPerformed(evt);
            }
        });

        jCboCliente_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCliente_ebgActionPerformed(evt);
            }
        });

        jLabel2.setText("Data venda");

        jBtnIncluirProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluirProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProd_ebgActionPerformed(evt);
            }
        });

        jBtnIncluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_ebg.setText("Incluir");
        jBtnIncluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ebgActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnConfirmar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar_ebg))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtVenda_ebg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFmtData_ebg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCboVendedor_ebg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboCliente_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtTotal_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirProd_ebg)
                            .addComponent(jBtnAlterarProd_ebg)
                            .addComponent(jBtnExcluirProd_ebg))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtTotal_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCboCliente_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtVenda_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboVendedor_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtData_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jBtnIncluirProd_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterarProd_ebg)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnExcluirProd_ebg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar_ebg)
                        .addComponent(jBtnCancelar_ebg)
                        .addComponent(jBtnPesquisar_ebg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir_ebg)
                        .addComponent(jBtnAlterar_ebg)
                        .addComponent(jBtnExcluir_ebg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProd_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendaproduto_ebg jDlgVendaproduto_ebg = new JDlgVendaproduto_ebg(null, true);
        jDlgVendaproduto_ebg.setTitle("Alteração de Produtos");
        jDlgVendaproduto_ebg.setTelaAnterior(this);
        int linSel = jTable1.getSelectedRow();
        VendaprodutoEbg vendaprodutoEbg = (VendaprodutoEbg) vendaprodutoController_ebg.getBean(linSel);
        jDlgVendaproduto_ebg.beanView(vendaprodutoEbg);
        jDlgVendaproduto_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProd_ebgActionPerformed

    private void jCboVendedor_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedor_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedor_ebgActionPerformed

    private void jBtnExcluirProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProd_ebgActionPerformed
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow();
        if (linha == -1){
            Util_ebg.mensagem("Nenhuma linha selecionada");
        }else{
            if(Util_ebg.perguntar("Confirmar exclusão do produto?") == true){
                vendaprodutoController_ebg.removeBean(linha);
            }
        }
    }//GEN-LAST:event_jBtnExcluirProd_ebgActionPerformed

    private void jBtnAlterar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ebgActionPerformed
        Util_ebg.habilitar(true, jBtnConfirmar_ebg, jBtnCancelar_ebg, jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        if (vendaEbg != null) {
            incluindo = false;
        } else {
            Util_ebg.mensagem("Deve ser realizada uma pesquisa antes");
        }
    }//GEN-LAST:event_jBtnAlterar_ebgActionPerformed

    private void jBtnExcluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ebgActionPerformed
        if (vendaEbg != null) {
            if (Util_ebg.perguntar("Deseja excluir o pedido ?") == true) {
                Vendaproduto_DAO vendaproduto_DAO = new Vendaproduto_DAO();
                VendaprodutoEbg vendaprodutoEbg;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    vendaprodutoEbg = vendaprodutoController_ebg.getBean(linha);
                    vendaproduto_DAO.delete(vendaprodutoEbg);
                }
                venda_DAO.delete(vendaEbg);
            }
        } else {
            Util_ebg.mensagem("Deve ser realizada uma pesquisa antes");
        }
        Util_ebg.limparCampos(jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        vendaEbg = null;
    }//GEN-LAST:event_jBtnExcluir_ebgActionPerformed

    private void jBtnConfirmar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ebgActionPerformed
        // TODO add your handling code here:
        vendaEbg = viewBean();

        if (incluindo == true) {
            venda_DAO.insert(vendaEbg);
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                vendaprodutoEbg = vendaprodutoController_ebg.getBean(linha);
                vendaprodutoEbg.setVendaEbg(vendaEbg);
                vendaproduto_DAO.insert(vendaprodutoEbg);
            }
        } else {
            venda_DAO.update(vendaEbg);
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                vendaprodutoEbg = vendaprodutoController_ebg.getBean(linha);
                vendaprodutoEbg.setVendaEbg(vendaEbg);
                this.vendaproduto_DAO.update(vendaprodutoEbg);
            }
        }
        vendaprodutoController_ebg.setList(new ArrayList());
        vendaEbg = null;
        Util_ebg.habilitar(true, jBtnIncluirProd_ebg, jBtnAlterarProd_ebg, jBtnExcluirProd_ebg, jBtnConfirmar_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnCancelar_ebg, jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.limparCampos(jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        
    }//GEN-LAST:event_jBtnConfirmar_ebgActionPerformed

    private void jBtnCancelar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ebgActionPerformed
        Util_ebg.limparCampos(jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        vendaprodutoController_ebg.setList(new ArrayList());
        vendaEbg = null;
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.habilitar(false, jBtnIncluirProd_ebg, jBtnAlterarProd_ebg, jBtnExcluirProd_ebg, jBtnConfirmar_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnCancelar_ebg, jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
    }//GEN-LAST:event_jBtnCancelar_ebgActionPerformed

    private void jBtnPesquisar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ebgActionPerformed
        JDlgVendaPesquisar_ebg jDlgVendaPesquisar_ebg = new JDlgVendaPesquisar_ebg(null, true);
        jDlgVendaPesquisar_ebg.setTelaAnterior(this);
        jDlgVendaPesquisar_ebg.setVisible(true);
        
        Util_ebg.habilitar(true, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnCancelar_ebg, jBtnPesquisar_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnConfirmar_ebg);
    }//GEN-LAST:event_jBtnPesquisar_ebgActionPerformed

    private void jCboCliente_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCliente_ebgActionPerformed
        
    }//GEN-LAST:event_jCboCliente_ebgActionPerformed

    private void jBtnIncluirProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProd_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendaproduto_ebg jDlgVendaproduto_ebg = new JDlgVendaproduto_ebg(null, true);
        jDlgVendaproduto_ebg.setTitle("Inclusão de Produtos");
        jDlgVendaproduto_ebg.setTelaAnterior(this);
        jDlgVendaproduto_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProd_ebgActionPerformed

    private void jBtnIncluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ebgActionPerformed
        Util_ebg.habilitar(true, jBtnIncluirProd_ebg, jBtnAlterarProd_ebg, jBtnExcluirProd_ebg, jBtnConfirmar_ebg, jBtnCancelar_ebg, jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
        vendaprodutoController_ebg.setList(new ArrayList());
        jTxtVenda_ebg.grabFocus();
        incluindo = true;
        vendaEbg = new VendaEbg();
        Util_ebg.limparCampos(jTxtVenda_ebg, jFmtData_ebg, jCboVendedor_ebg, jCboCliente_ebg, jTxtTotal_ebg);
    }//GEN-LAST:event_jBtnIncluir_ebgActionPerformed

    private void jFmtData_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtData_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtData_ebgActionPerformed

    private void jTxtVenda_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVenda_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtVenda_ebgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVenda_ebg dialog = new JDlgVenda_ebg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterarProd_ebg;
    private javax.swing.JButton jBtnAlterar_ebg;
    private javax.swing.JButton jBtnCancelar_ebg;
    private javax.swing.JButton jBtnConfirmar_ebg;
    private javax.swing.JButton jBtnExcluirProd_ebg;
    private javax.swing.JButton jBtnExcluir_ebg;
    private javax.swing.JButton jBtnIncluirProd_ebg;
    private javax.swing.JButton jBtnIncluir_ebg;
    private javax.swing.JButton jBtnPesquisar_ebg;
    private javax.swing.JComboBox<ClienteEbg> jCboCliente_ebg;
    private javax.swing.JComboBox<VendedorEbg> jCboVendedor_ebg;
    private javax.swing.JFormattedTextField jFmtData_ebg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtTotal_ebg;
    private javax.swing.JTextField jTxtVenda_ebg;
    // End of variables declaration//GEN-END:variables
}
