/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteEbg;
import bean.VendaEbg;
import bean.VendaprodutoEbg;
import dao.Venda_DAO;
import dao.Vendaproduto_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author user
 */
public class JDlgVenda_ebg extends javax.swing.JDialog {
    MaskFormatter mascaraData;
    private boolean incluindo;
    
    VendaEbg vendaEbg;
    Venda_DAO Venda_DAO;
    VendaController_ebg vendaController_ebg;
    VendaprodutoEbg vendaprodutoEbg;
    Vendaproduto_DAO vendaproduto_DAO;
    VendaprodutoController_ebg vendaprodutoController_ebg;
    ClienteEbg ClienteEbg;
    JDlgVendaPesquisar_ebg jDlgVendaPesquisa;
    JDlgVendaproduto_ebg JDlgVendaProduto_ebg;
    /**
     * Creates new form JDlgVendas
     */
    public JDlgVenda_ebg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Venda viewBean() {
        Venda venda = new Venda();
        
        int id = Integer.valueOf(jTxtVenda.getText());
        venda.setId_venda(id);
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            venda.setData(formato.parse(jFmtData.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        venda.setVendedor(jCboVendedor.getSelectedIndex());
        venda.setCliente(jCboCliente.getSelectedIndex());
        venda.setTotal_venda(jTxtTotal.getText());
        
        return venda;
    }
    
    public void beanView(Venda venda){
        String valor = String.valueOf(venda.getId_venda());
        
        jTxtVenda.setText(valor);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtData.setText(formato.format (venda.getData()));
        jCboCliente.setSelectedIndex(venda.getVendedor());
        jCboVendedor.setSelectedIndex(venda.getVendedor());
        jTxtTotal.setText(venda.getTotal_venda());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFmtData_ebg = new javax.swing.JFormattedTextField();
        jBtnAlterarProd_ebg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTxtTotal_ebg = new javax.swing.JTextField();
        jCboVendedor_ebg = new javax.swing.JComboBox<Caixa>();
        jBtnExcluirProd_ebg = new javax.swing.JButton();
        jBtnAlterar_ebg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnExcluir_ebg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnConfirmar_ebg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtVenda_ebg = new javax.swing.JTextField();
        jBtnCancelar_ebg = new javax.swing.JButton();
        jBtnPesquisar_ebg = new javax.swing.JButton();
        jCboCliente_ebg = new javax.swing.JComboBox<Cliente>();
        jLabel2 = new javax.swing.JLabel();
        jBtnIncluirProd_ebg = new javax.swing.JButton();
        jBtnIncluir_ebg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFmtData_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtData_ebgActionPerformed(evt);
            }
        });

        jBtnAlterarProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterarProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProd_ebgActionPerformed(evt);
            }
        });

        jLabel3.setText("Vendedor");

        jCboVendedor_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboVendedor_ebgActionPerformed(evt);
            }
        });

        jBtnExcluirProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluirProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirProd_ebgActionPerformed(evt);
            }
        });

        jBtnAlterar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_ebg.setText("Alerar");
        jBtnAlterar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ebgActionPerformed(evt);
            }
        });

        jLabel1.setText("Num venda");

        jBtnExcluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_ebg.setText("Excluir");
        jBtnExcluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ebgActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnConfirmar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/05 - ok.png"))); // NOI18N
        jBtnConfirmar_ebg.setText("Confirmar");
        jBtnConfirmar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ebgActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        jBtnCancelar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_ebg.setText("Cancelar");
        jBtnCancelar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ebgActionPerformed(evt);
            }
        });

        jBtnPesquisar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_ebg.setText("Pesquisar");
        jBtnPesquisar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ebgActionPerformed(evt);
            }
        });

        jCboCliente_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCliente_ebgActionPerformed(evt);
            }
        });

        jLabel2.setText("Data venda");

        jBtnIncluirProd_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluirProd_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProd_ebgActionPerformed(evt);
            }
        });

        jBtnIncluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_ebg.setText("Incluir");
        jBtnIncluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ebgActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnConfirmar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar_ebg))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtVenda_ebg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFmtData_ebg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCboVendedor_ebg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboCliente_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtTotal_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirProd_ebg)
                            .addComponent(jBtnAlterarProd_ebg)
                            .addComponent(jBtnExcluirProd_ebg))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtTotal_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCboCliente_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtVenda_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboVendedor_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtData_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jBtnIncluirProd_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterarProd_ebg)
                        .addGap(20, 20, 20)
                        .addComponent(jBtnExcluirProd_ebg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar_ebg)
                        .addComponent(jBtnCancelar_ebg)
                        .addComponent(jBtnPesquisar_ebg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir_ebg)
                        .addComponent(jBtnAlterar_ebg)
                        .addComponent(jBtnExcluir_ebg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProd_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendaproduto jDlgVendaproduto = new JDlgVendaproduto(null, true);
        jDlgVendaproduto.setTitle("Alterar Produto");
        jDlgVendaproduto.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProd_ebgActionPerformed

    private void jCboVendedor_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboVendedor_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboVendedor_ebgActionPerformed

    private void jBtnExcluirProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirProd_ebgActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Excluir o resgistro?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (resp == JOptionPane.YES_OPTION){
        }else{
            JOptionPane.showMessageDialog(null, "Exclusão cancelada", "Alerta", 2);
        }
    }//GEN-LAST:event_jBtnExcluirProd_ebgActionPerformed

    private void jBtnAlterar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ebgActionPerformed
        // TODO add your handling code here:
        habilitar();
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_ebgActionPerformed

    private void jBtnExcluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ebgActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Confirmar excluir?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            Venda venda = viewBean();
            Venda_DAO venda_DAO = new Venda_DAO();
            venda_DAO.delete(venda);
        } else {
            JOptionPane.showMessageDialog(null, "Exclusão cancelada!", "ALERTA", 2);
        }
    }//GEN-LAST:event_jBtnExcluir_ebgActionPerformed

    private void jBtnConfirmar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ebgActionPerformed
        // TODO add your handling code here:
        Venda venda = viewBean();

        Venda_DAO venda_DAO = new Venda_DAO();
        venda_DAO.insert(venda);

        if (incluindo == true) {
            venda_DAO.insert(venda);
        } else {
            venda_DAO.update(venda);
        }

        desabilitar();
    }//GEN-LAST:event_jBtnConfirmar_ebgActionPerformed

    private void jBtnCancelar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ebgActionPerformed
        // TODO add your handling code here:
        limparCampos();
        desabilitar();
    }//GEN-LAST:event_jBtnCancelar_ebgActionPerformed

    private void jBtnPesquisar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ebgActionPerformed
        // TODO add your handling code here:
        //        String resp = JOptionPane.showInputDialog(null, "Entre com o código");
        //        Venda_DAO venda_DAO = new Venda_DAO();
        //        int id = Integer.valueOf(resp);
        //        Venda venda = (Venda) venda_DAO.list( id );
        //        beanView(venda);
        JDlgVendaPesquisar jDlgVendaPesquisar = new JDlgVendaPesquisar(null, true);
        jDlgVendaPesquisar.setTelaAnterior(this);
        jDlgVendaPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisar_ebgActionPerformed

    private void jCboCliente_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCliente_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCliente_ebgActionPerformed

    private void jBtnIncluirProd_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProd_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendaproduto jDlgVendaproduto = new JDlgVendaproduto(null, true);
        jDlgVendaproduto.setTitle("Incluir Produto");
        jDlgVendaproduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProd_ebgActionPerformed

    private void jBtnIncluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ebgActionPerformed
        // TODO add your handling code here:
        habilitar();
        limparCampos();
    }//GEN-LAST:event_jBtnIncluir_ebgActionPerformed

    private void jFmtData_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtData_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtData_ebgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVenda_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVenda_ebg dialog = new JDlgVenda_ebg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterarProd_ebg;
    private javax.swing.JButton jBtnAlterar_ebg;
    private javax.swing.JButton jBtnCancelar_ebg;
    private javax.swing.JButton jBtnConfirmar_ebg;
    private javax.swing.JButton jBtnExcluirProd_ebg;
    private javax.swing.JButton jBtnExcluir_ebg;
    private javax.swing.JButton jBtnIncluirProd_ebg;
    private javax.swing.JButton jBtnIncluir_ebg;
    private javax.swing.JButton jBtnPesquisar_ebg;
    private javax.swing.JComboBox<Cliente> jCboCliente_ebg;
    private javax.swing.JComboBox<Caixa> jCboVendedor_ebg;
    private javax.swing.JFormattedTextField jFmtData_ebg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtTotal_ebg;
    private javax.swing.JTextField jTxtVenda_ebg;
    // End of variables declaration//GEN-END:variables
}
