/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author u08004655122
 */

import bean.UsuarioEbg;
import dao.Usuario_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util_ebg;

/**
 *
 * @author u08004655122
 */
public class JDlgUsuario_ebg extends javax.swing.JDialog {
    private boolean incluindo;
    
    private MaskFormatter mascaraCpf, mascaraNascimento;
    public UsuarioEbg usuarioEbg;
    public Usuario_DAO usuario_DAO;

    /**
     * Creates new form JDlgUsuario_ebg
     */
    public JDlgUsuario_ebg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Usuario_DAO usuario_DAO = new Usuario_DAO();
        
        Util_ebg.limparCampos(jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(false, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnPesquisar_ebg);
        
        setTitle("Cadastro de usuários");
        setLocationRelativeTo(null);

        try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraNascimento = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpf_ebg.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtNascimento_ebg.setFormatterFactory(new DefaultFormatterFactory(mascaraNascimento));
   
    }

    public UsuarioEbg viewBean() {
        UsuarioEbg usuarioEbg = new UsuarioEbg();

        usuarioEbg.setIdusuarioEbg(Util_ebg.strInt(jTxtCodigo_ebg.getText()));
        usuarioEbg.setNomeEbg(jTxtNome_ebg.getText());
        usuarioEbg.setApelidoEbg(jTxtApelido_ebg.getText());
        usuarioEbg.setCpfEbg(jFmtCpf_ebg.getText());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try {
            usuarioEbg.setNascimentoEbg (formato.parse(jFmtNascimento_ebg.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        usuarioEbg.setNivelEbg(jCboNivel_ebg.getSelectedIndex());
        usuarioEbg.setAtivoEbg( jChbAtivo_ebg.isSelected() == true ? "S" : "N");
        usuarioEbg.setSenhaEbg(jPwfSenha_ebg.getText());

        return usuarioEbg;

    }

    public void beanView(UsuarioEbg usuarioEbg) {
        String id = String.valueOf(usuarioEbg.getIdusuarioEbg());

        jTxtCodigo_ebg.setText(id);
        jTxtNome_ebg.setText(usuarioEbg.getNomeEbg());
        jTxtApelido_ebg.setText(usuarioEbg.getApelidoEbg());
        jFmtCpf_ebg.setText(usuarioEbg.getCpfEbg());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtNascimento_ebg.setText(formato.format(usuarioEbg.getNascimentoEbg()));
        
        jCboNivel_ebg.setSelectedIndex(usuarioEbg.getNivelEbg()); //nao deu erro pq no bd nivel é inteiro, o index pega o indice corrente e peg os itens do nivel
        
        if (usuarioEbg.getAtivoEbg().equals("S") == true) {
            jChbAtivo_ebg.setSelected(true);
        } else {
            jChbAtivo_ebg.setSelected(false);
        }
        jPwfSenha_ebg.setText(usuarioEbg.getSenhaEbg());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFmtNascimento_ebg = new javax.swing.JFormattedTextField();
        jBtnPesquisar_ebg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPwfSenha_ebg = new javax.swing.JPasswordField();
        jTxtCodigo_ebg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCboNivel_ebg = new javax.swing.JComboBox<>();
        jTxtNome_ebg = new javax.swing.JTextField();
        jChbAtivo_ebg = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jBtnIncluir_ebg = new javax.swing.JButton();
        jTxtApelido_ebg = new javax.swing.JTextField();
        jBtnAlterar_ebg = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnExcluir_ebg = new javax.swing.JButton();
        jFmtCpf_ebg = new javax.swing.JFormattedTextField();
        jBtnConfirmar_ebg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnCancelar_ebg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnPesquisar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/06 - pesquisar.png"))); // NOI18N
        jBtnPesquisar_ebg.setText("Pesquisar");
        jBtnPesquisar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_ebgActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha");

        jLabel1.setText("Código");

        jPwfSenha_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwfSenha_ebgActionPerformed(evt);
            }
        });

        jTxtCodigo_ebg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtCodigo_ebgFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtCodigo_ebgFocusLost(evt);
            }
        });
        jTxtCodigo_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigo_ebgActionPerformed(evt);
            }
        });

        jLabel7.setText("Nível");

        jLabel2.setText("Nome");

        jCboNivel_ebg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jCboNivel_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboNivel_ebgActionPerformed(evt);
            }
        });

        jChbAtivo_ebg.setText("Ativo");
        jChbAtivo_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbAtivo_ebgActionPerformed(evt);
            }
        });

        jLabel3.setText("Apelido");

        jBtnIncluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/04 - incluir.png"))); // NOI18N
        jBtnIncluir_ebg.setText("Incluir");
        jBtnIncluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_ebgActionPerformed(evt);
            }
        });

        jTxtApelido_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApelido_ebgActionPerformed(evt);
            }
        });

        jBtnAlterar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/01 - alterar.png"))); // NOI18N
        jBtnAlterar_ebg.setText("Alterar");
        jBtnAlterar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_ebgActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        jBtnExcluir_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/02 - excluir.png"))); // NOI18N
        jBtnExcluir_ebg.setText("Excluir");
        jBtnExcluir_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_ebgActionPerformed(evt);
            }
        });

        jFmtCpf_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpf_ebgActionPerformed(evt);
            }
        });

        jBtnConfirmar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/05 - ok.png"))); // NOI18N
        jBtnConfirmar_ebg.setText("Confirmar");
        jBtnConfirmar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_ebgActionPerformed(evt);
            }
        });

        jLabel5.setText("Nascimento");

        jBtnCancelar_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jBtnCancelar_ebg.setText("Cancelar");
        jBtnCancelar_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_ebgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(164, 164, 164)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtCpf_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jFmtNascimento_ebg)
                                    .addComponent(jCboNivel_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPwfSenha_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigo_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChbAtivo_ebg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtNome_ebg, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtApelido_ebg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_ebg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar_ebg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtCodigo_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtNome_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtApelido_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCpf_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtNascimento_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenha_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboNivel_ebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivo_ebg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir_ebg)
                    .addComponent(jBtnAlterar_ebg)
                    .addComponent(jBtnExcluir_ebg)
                    .addComponent(jBtnConfirmar_ebg)
                    .addComponent(jBtnCancelar_ebg)
                    .addComponent(jBtnPesquisar_ebg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_ebgActionPerformed
        JDlgUsuarioPesquisar_ebg jDlgUsuarioPesquisar_ebg = new JDlgUsuarioPesquisar_ebg(null, true);
        jDlgUsuarioPesquisar_ebg.setTelaAnterior(this);
        jDlgUsuarioPesquisar_ebg.setVisible(true);
        
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnCancelar_ebg, jBtnPesquisar_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnConfirmar_ebg);
    }//GEN-LAST:event_jBtnPesquisar_ebgActionPerformed

    private void jPwfSenha_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwfSenha_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwfSenha_ebgActionPerformed

    private void jTxtCodigo_ebgFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo_ebgFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_ebgFocusGained

    private void jTxtCodigo_ebgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtCodigo_ebgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_ebgFocusLost

    private void jTxtCodigo_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigo_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigo_ebgActionPerformed

    private void jCboNivel_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboNivel_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboNivel_ebgActionPerformed

    private void jChbAtivo_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbAtivo_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbAtivo_ebgActionPerformed

    private void jBtnIncluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_ebgActionPerformed
        // TODO add your handling code here:
        //habilitar();
        Util_ebg.habilitar(true,  jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.limparCampos(jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtNascimento_ebg, jPwfSenha_ebg, jChbAtivo_ebg, jCboNivel_ebg);
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_ebgActionPerformed

    private void jTxtApelido_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApelido_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApelido_ebgActionPerformed

    private void jBtnAlterar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_ebgActionPerformed
        // TODO add your handling code here:
        //habilitar();
        Util_ebg.habilitar(true,  jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(false, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_ebgActionPerformed

    private void jBtnExcluir_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_ebgActionPerformed
        Util_ebg.habilitar(false,  jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
           
        if (Util_ebg.perguntar("Deseja excluir o projeto?") == true){
            UsuarioEbg usuarioEbg = viewBean();
            Usuario_DAO usuario_DAO = new Usuario_DAO();
            usuario_DAO.delete(usuarioEbg);
            Util_ebg.mensagem("Exclusão executada com sucesso.");
            }else {
                Util_ebg.mensagem("Exclusão cancelada.");
            }
        Util_ebg.limparCampos(jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
    }//GEN-LAST:event_jBtnExcluir_ebgActionPerformed

    private void jBtnConfirmar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_ebgActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        UsuarioEbg usuarioEbg = viewBean();
        Usuario_DAO usuario_DAO = new Usuario_DAO();
        
        if (incluindo == true) {
            usuario_DAO.insert(usuarioEbg);
        } else {
            usuario_DAO.update(usuarioEbg);
        }

        Util_ebg.habilitar(false,  jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.limparCampos(jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        
        Util_ebg.mensagem("Incluido com sucesso!");
    }//GEN-LAST:event_jBtnConfirmar_ebgActionPerformed

    private void jBtnCancelar_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_ebgActionPerformed
        // TODO add your handling code here:
        //desabilitar();
        Util_ebg.habilitar(false,  jBtnCancelar_ebg, jBtnConfirmar_ebg, jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.habilitar(true, jBtnIncluir_ebg, jBtnAlterar_ebg, jBtnExcluir_ebg, jBtnPesquisar_ebg);
        Util_ebg.limparCampos(jTxtCodigo_ebg, jTxtNome_ebg, jTxtApelido_ebg, jFmtCpf_ebg, jFmtNascimento_ebg, jCboNivel_ebg,jChbAtivo_ebg, jPwfSenha_ebg);
        Util_ebg.mensagem("Operação cancelada");
    }//GEN-LAST:event_jBtnCancelar_ebgActionPerformed

    private void jFmtCpf_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpf_ebgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpf_ebgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuario_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuario_ebg dialog = new JDlgUsuario_ebg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_ebg;
    private javax.swing.JButton jBtnCancelar_ebg;
    private javax.swing.JButton jBtnConfirmar_ebg;
    private javax.swing.JButton jBtnExcluir_ebg;
    private javax.swing.JButton jBtnIncluir_ebg;
    private javax.swing.JButton jBtnPesquisar_ebg;
    private javax.swing.JComboBox<String> jCboNivel_ebg;
    private javax.swing.JCheckBox jChbAtivo_ebg;
    private javax.swing.JFormattedTextField jFmtCpf_ebg;
    private javax.swing.JFormattedTextField jFmtNascimento_ebg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPwfSenha_ebg;
    private javax.swing.JTextField jTxtApelido_ebg;
    private javax.swing.JTextField jTxtCodigo_ebg;
    private javax.swing.JTextField jTxtNome_ebg;
    // End of variables declaration//GEN-END:variables
}
