package bean;
// Generated 01/12/2023 16:33:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorEbg generated by hbm2java
 */
@Entity
@Table(name="vendedor_ebg"
    ,catalog="db_estefani_gimenez"
)
public class VendedorEbg  implements java.io.Serializable {


     private int idvendedorEbg;
     private String nomeEbg;
     private String cpfEbg;
     private String celularEbg;
     private Date dataexpedienteEbg;
     private double comissaoEbg;

    public VendedorEbg() {
    }

	
    public VendedorEbg(int idvendedorEbg, String nomeEbg, String cpfEbg, String celularEbg, Date dataexpedienteEbg, double comissaoEbg) {
        this.idvendedorEbg = idvendedorEbg;
        this.nomeEbg = nomeEbg;
        this.cpfEbg = cpfEbg;
        this.celularEbg = celularEbg;
        this.dataexpedienteEbg = dataexpedienteEbg;
        this.comissaoEbg = comissaoEbg;
    }
    
     @Id 

    
    @Column(name="idvendedor_ebg", unique=true, nullable=false)
    public int getIdvendedorEbg() {
        return this.idvendedorEbg;
    }
    
    public void setIdvendedorEbg(int idvendedorEbg) {
        this.idvendedorEbg = idvendedorEbg;
    }

    
    @Column(name="nome_ebg", nullable=false, length=80)
    public String getNomeEbg() {
        return this.nomeEbg;
    }
    
    public void setNomeEbg(String nomeEbg) {
        this.nomeEbg = nomeEbg;
    }

    
    @Column(name="cpf_ebg", nullable=false, length=80)
    public String getCpfEbg() {
        return this.cpfEbg;
    }
    
    public void setCpfEbg(String cpfEbg) {
        this.cpfEbg = cpfEbg;
    }

    
    @Column(name="celular_ebg", nullable=false, length=80)
    public String getCelularEbg() {
        return this.celularEbg;
    }
    
    public void setCelularEbg(String celularEbg) {
        this.celularEbg = celularEbg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataexpediente_ebg", nullable=false, length=10)
    public Date getDataexpedienteEbg() {
        return this.dataexpedienteEbg;
    }
    
    public void setDataexpedienteEbg(Date dataexpedienteEbg) {
        this.dataexpedienteEbg = dataexpedienteEbg;
    }

    
    @Column(name="comissao_ebg", precision=10)
    public double getComissaoEbg() {
        return this.comissaoEbg;
    }
    
    public void setComissaoEbg(double comissaoEbg) {
        this.comissaoEbg = comissaoEbg;
    }
}


