package bean;
// Generated 01/12/2023 16:33:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendaEbg generated by hbm2java
 */
@Entity
@Table(name="venda_ebg"
    ,catalog="db_estefani_gimenez"
)
public class VendaEbg  implements java.io.Serializable {


     private int idvendaEbg;
     private ClienteEbg clienteEbg;
     private VendedorEbg vendedorEbg;
     private Date dataEbg;
     private double totalvendaEbg;

    public VendaEbg() {
    }

	
    public VendaEbg(int idvendaEbg, ClienteEbg clienteEbg, VendedorEbg vendedorEbg, Date dataEbg, double totalvendaEbg) {
        this.idvendaEbg = idvendaEbg;
        this.clienteEbg = clienteEbg;
        this.vendedorEbg = vendedorEbg;
        this.dataEbg = dataEbg;
        this.totalvendaEbg = totalvendaEbg;
    }
   
     @Id 

    
    @Column(name="idvenda_ebg", unique=true, nullable=false)
    public int getIdvendaEbg() {
        return this.idvendaEbg;
    }
    
    public void setIdvendaEbg(int idvendaEbg) {
        this.idvendaEbg = idvendaEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_ebg", nullable=false)
    public ClienteEbg getClienteEbg() {
        return this.clienteEbg;
    }
    
    public void setClienteEbg(ClienteEbg clienteEbg) {
        this.clienteEbg = clienteEbg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_ebg", nullable=false)
    public VendedorEbg getVendedorEbg() {
        return this.vendedorEbg;
    }
    
    public void setVendedorEbg(VendedorEbg vendedorEbg) {
        this.vendedorEbg = vendedorEbg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ebg", nullable=false, length=10)
    public Date getDataEbg() {
        return this.dataEbg;
    }
    
    public void setDataEbg(Date dataEbg) {
        this.dataEbg = dataEbg;
    }

    
    @Column(name="totalvenda_ebg", precision=10)
    public double getTotalvendaEbg() {
        return this.totalvendaEbg;
    }
    
    public void setTotalvendaEbg(double totalvendaEbg) {
        this.totalvendaEbg = totalvendaEbg;
    }

}


